title: hugo tocccs
baseURL: https://awfulthings.github.io/fakin-hugo/
languageCode: cs-cz
publishDir: docs

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Description of my new site.
  authors: Authors

